"use strict";

const result1 = "8" + 2;
const result2 = "8" - 2;
const result3 = Number("8") + 2;
const result4 = "12" > "3";
const result5 = 12 === "12";
const result6 = Number("");
const result7 = Number("text");
const result8 = Boolean("false");
const result9 = typeof null;
const result10 = typeof NaN;

console.log("---------");
console.log("Результат:", result1);
console.log("Тип результата:", typeof result1);
console.log("---------");
console.log("Результат:", result2);
console.log("Тип результата:", typeof result2);
console.log("---------");
console.log("Результат:", result3);
console.log("Тип результата:", typeof result3);
console.log("---------");
console.log("Результат:", result4);
console.log("Тип результата:", typeof result4);
console.log("---------");
console.log("Результат:", result5);
console.log("Тип результата:", typeof result5);
console.log("---------");
console.log("Результат:", result6);
console.log("Тип результата:", typeof result6);
console.log("---------");
console.log("Результат:", result7);
console.log("Тип результата:", typeof result7);
console.log("---------");
console.log("Результат:", result8);
console.log("Тип результата:", typeof result8);
console.log("---------");
console.log("Результат:", result9);
console.log("Тип результата:", typeof result9);
console.log("---------");
console.log("Результат:", result10);
console.log("Тип результата:", typeof result10);
console.log("---------");